=begin
CloudBoost Application API

Power your web or mobile application backend with cloudboost Database Service

OpenAPI spec version: 1.0.0
Contact: ben@cloudboost.io
Generated by: https://github.com/swagger-api/swagger-codegen.git

License: MIT
http://opensource.org/licenses/MIT

Terms of Service: https://cloudboost.io

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SwaggerClient::CacheItem
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'CacheItem' do
  before do
    # run before each test
    @instance = SwaggerClient::CacheItem.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CacheItem' do
    it 'should create an instact of CacheItem' do
      @instance.should be_a(SwaggerClient::CacheItem) 
    end
  end
  describe 'test attribute "key"' do
    it 'should work' do
       # assertion here
       # should be_a()
       # should be_nil
       # should ==
       # should_not ==
    end
  end

  describe 'test attribute "value"' do
    it 'should work' do
       # assertion here
       # should be_a()
       # should be_nil
       # should ==
       # should_not ==
    end
  end

end

