=begin
CloudBoost Application API

Power your web or mobile application backend with cloudboost Database Service

OpenAPI spec version: 1.0.0
Contact: ben@cloudboost.io
Generated by: https://github.com/swagger-api/swagger-codegen.git

License: MIT
http://opensource.org/licenses/MIT

Terms of Service: https://cloudboost.io

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SwaggerClient::CloudObject
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'CloudObject' do
  before do
    # run before each test
    @instance = SwaggerClient::CloudObject.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CloudObject' do
    it 'should create an instact of CloudObject' do
      @instance.should be_a(SwaggerClient::CloudObject) 
    end
  end
end

