#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "SWGQuery.h"


@protocol SWGCloudQuery
@end

@interface SWGCloudQuery : SWGObject


@property(nonatomic) NSString* key;

@property(nonatomic) NSNumber* skip;

@property(nonatomic) NSNumber* limit;

@property(nonatomic) SWGQuery* query;

@property(nonatomic) NSObject* sort;

@property(nonatomic) NSObject* select;

@end
