#import <Foundation/Foundation.h>
#import "SWGCloudRole.h"
#import "SWGRoleBody.h"
#import "SWGObject.h"
#import "SWGApiClient.h"


/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Do not edit the class manually.
 */

@interface SWGCloudRoleApi: NSObject

@property(nonatomic, assign)SWGApiClient *apiClient;

-(instancetype) initWithApiClient:(SWGApiClient *)apiClient;
-(void) addHeader:(NSString*)value forKey:(NSString*)key;
-(unsigned long) requestQueueSize;
+(SWGCloudRoleApi*) apiWithHeader:(NSString*)headerValue key:(NSString*)key;
+(SWGCloudRoleApi*) sharedAPI;
///
///
/// create a new cloudrole
/// 
///
/// @param appId ID of app
/// @param body request body
/// 
///
/// @return SWGCloudRole*
-(NSNumber*) createRoleWithAppId: (NSString*) appId
    body: (SWGRoleBody*) body
    completionHandler: (void (^)(SWGCloudRole* output, NSError* error)) handler;



@end
