#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "SWGFilterBody.h"


@protocol SWGCloudSearch
@end

@interface SWGCloudSearch : SWGObject


@property(nonatomic) SWGFilterBody* query;

@property(nonatomic) NSArray* /* NSString */ sort;

@property(nonatomic) NSString* collectionName;

@property(nonatomic) NSString* key;

@property(nonatomic) NSNumber* skip;

@property(nonatomic) NSNumber* limit;

@end
