#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "SWGBoolFilter.h"
#import "SWGBoolQuery.h"


@protocol SWGFiltered
@end

@interface SWGFiltered : SWGObject


@property(nonatomic) SWGBoolQuery* query;

@property(nonatomic) SWGBoolFilter* filter;

@end
