#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "SWGModifiedQueue.h"


@protocol SWGModifiedQueueBody
@end

@interface SWGModifiedQueueBody : SWGObject


@property(nonatomic) SWGModifiedQueue* document;

@property(nonatomic) NSString* key;

@end
