#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "SWGACL.h"
#import "SWGQueueMessage.h"


@protocol SWGQueue
@end

@interface SWGQueue : SWGObject


@property(nonatomic) NSString* _id;

@property(nonatomic) NSString* tableName;

@property(nonatomic) NSDate* createdAt;

@property(nonatomic) NSDate* updatedAt;

@property(nonatomic) SWGACL* aCL;

@property(nonatomic) NSString* type;

@property(nonatomic) NSDate* expires;

@property(nonatomic) NSString* queueType;

@property(nonatomic) NSString* retry;

@property(nonatomic) NSString* name;

@property(nonatomic) NSArray* /* NSString */ subscribers;

@property(nonatomic) NSArray<SWGQueueMessage>* messages;

@end
