#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol SWGRefreshMessageTimeoutBody
@end

@interface SWGRefreshMessageTimeoutBody : SWGObject


@property(nonatomic) NSNumber* timeout;

@property(nonatomic) NSString* key;

@end
