<?php
/**
 * CloudCacheApi
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2016 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Do not edit the class manually.
 */

namespace Swagger\Client\Api;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiClient;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * CloudCacheApi Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class CloudCacheApi
{

    /**
     * API Client
     * @var \Swagger\Client\ApiClient instance of the ApiClient
     */
    protected $apiClient;
  
    /**
     * Constructor
     * @param \Swagger\Client\ApiClient|null $apiClient The api client to use
     */
    function __construct($apiClient = null)
    {
        if ($apiClient == null) {
            $apiClient = new ApiClient();
            $apiClient->getConfig()->setHost('http://api.cloudboost.io/');
        }
  
        $this->apiClient = $apiClient;
    }
  
    /**
     * Get API client
     * @return \Swagger\Client\ApiClient get the API client
     */
    public function getApiClient()
    {
        return $this->apiClient;
    }
  
    /**
     * Set the API client
     * @param \Swagger\Client\ApiClient $apiClient set the API client
     * @return CloudCacheApi
     */
    public function setApiClient(ApiClient $apiClient)
    {
        $this->apiClient = $apiClient;
        return $this;
    }
  
    
    /**
     * clearCache
     *
     * clear all items from a cloud cache
     *
     * @param string $app_id Id of CloudApp (required)
     * @param string $cache_name Name of cache (required)
     * @param \Swagger\Client\Model\KeyBody $body master key of app (required)
     * @return \Swagger\Client\Model\CacheRequest[]
     * @throws \Swagger\Client\ApiException on non-2xx response
     */
    public function clearCache($app_id, $cache_name, $body)
    {
        list($response, $statusCode, $httpHeader) = $this->clearCacheWithHttpInfo ($app_id, $cache_name, $body);
        return $response; 
    }


    /**
     * clearCacheWithHttpInfo
     *
     * clear all items from a cloud cache
     *
     * @param string $app_id Id of CloudApp (required)
     * @param string $cache_name Name of cache (required)
     * @param \Swagger\Client\Model\KeyBody $body master key of app (required)
     * @return Array of \Swagger\Client\Model\CacheRequest[], HTTP status code, HTTP response headers (array of strings)
     * @throws \Swagger\Client\ApiException on non-2xx response
     */
    public function clearCacheWithHttpInfo($app_id, $cache_name, $body)
    {
        
        // verify the required parameter 'app_id' is set
        if ($app_id === null) {
            throw new \InvalidArgumentException('Missing the required parameter $app_id when calling clearCache');
        }
        // verify the required parameter 'cache_name' is set
        if ($cache_name === null) {
            throw new \InvalidArgumentException('Missing the required parameter $cache_name when calling clearCache');
        }
        // verify the required parameter 'body' is set
        if ($body === null) {
            throw new \InvalidArgumentException('Missing the required parameter $body when calling clearCache');
        }
  
        // parse inputs
        $resourcePath = "cache/{app_id}/{cache_name}/clear";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = ApiClient::selectHeaderAccept(array('application/json'));
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = ApiClient::selectHeaderContentType(array('application/json'));
  
        
        
        // path params
        
        if ($app_id !== null) {
            $resourcePath = str_replace(
                "{" . "app_id" . "}",
                $this->apiClient->getSerializer()->toPathValue($app_id),
                $resourcePath
            );
        }// path params
        
        if ($cache_name !== null) {
            $resourcePath = str_replace(
                "{" . "cache_name" . "}",
                $this->apiClient->getSerializer()->toPathValue($cache_name),
                $resourcePath
            );
        }
        // default format to json
        $resourcePath = str_replace("{format}", "json", $resourcePath);

        
        // body params
        $_tempBody = null;
        if (isset($body)) {
            $_tempBody = $body;
        }
  
        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath, 'DELETE',
                $queryParams, $httpBody,
                $headerParams, '\Swagger\Client\Model\CacheRequest[]'
            );
            
            if (!$response) {
                return array(null, $statusCode, $httpHeader);
            }

            return array(\Swagger\Client\ObjectSerializer::deserialize($response, '\Swagger\Client\Model\CacheRequest[]', $httpHeader), $statusCode, $httpHeader);
            
        } catch (ApiException $e) {
            switch ($e->getCode()) { 
            case 200:
                $data = \Swagger\Client\ObjectSerializer::deserialize($e->getResponseBody(), '\Swagger\Client\Model\CacheRequest[]', $e->getResponseHeaders());
                $e->setResponseObject($data);
                break;
            }
  
            throw $e;
        }
    }
    
    /**
     * createCache
     *
     * create a cloud cache
     *
     * @param string $app_id Id of CloudApp (required)
     * @param string $cache_name Name of cache (required)
     * @param \Swagger\Client\Model\KeyBody $body master key of app (required)
     * @return \Swagger\Client\Model\Cache
     * @throws \Swagger\Client\ApiException on non-2xx response
     */
    public function createCache($app_id, $cache_name, $body)
    {
        list($response, $statusCode, $httpHeader) = $this->createCacheWithHttpInfo ($app_id, $cache_name, $body);
        return $response; 
    }


    /**
     * createCacheWithHttpInfo
     *
     * create a cloud cache
     *
     * @param string $app_id Id of CloudApp (required)
     * @param string $cache_name Name of cache (required)
     * @param \Swagger\Client\Model\KeyBody $body master key of app (required)
     * @return Array of \Swagger\Client\Model\Cache, HTTP status code, HTTP response headers (array of strings)
     * @throws \Swagger\Client\ApiException on non-2xx response
     */
    public function createCacheWithHttpInfo($app_id, $cache_name, $body)
    {
        
        // verify the required parameter 'app_id' is set
        if ($app_id === null) {
            throw new \InvalidArgumentException('Missing the required parameter $app_id when calling createCache');
        }
        // verify the required parameter 'cache_name' is set
        if ($cache_name === null) {
            throw new \InvalidArgumentException('Missing the required parameter $cache_name when calling createCache');
        }
        // verify the required parameter 'body' is set
        if ($body === null) {
            throw new \InvalidArgumentException('Missing the required parameter $body when calling createCache');
        }
  
        // parse inputs
        $resourcePath = "cache/{app_id}/{cache_name}/create";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = ApiClient::selectHeaderAccept(array('application/json'));
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = ApiClient::selectHeaderContentType(array('application/json'));
  
        
        
        // path params
        
        if ($app_id !== null) {
            $resourcePath = str_replace(
                "{" . "app_id" . "}",
                $this->apiClient->getSerializer()->toPathValue($app_id),
                $resourcePath
            );
        }// path params
        
        if ($cache_name !== null) {
            $resourcePath = str_replace(
                "{" . "cache_name" . "}",
                $this->apiClient->getSerializer()->toPathValue($cache_name),
                $resourcePath
            );
        }
        // default format to json
        $resourcePath = str_replace("{format}", "json", $resourcePath);

        
        // body params
        $_tempBody = null;
        if (isset($body)) {
            $_tempBody = $body;
        }
  
        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath, 'POST',
                $queryParams, $httpBody,
                $headerParams, '\Swagger\Client\Model\Cache'
            );
            
            if (!$response) {
                return array(null, $statusCode, $httpHeader);
            }

            return array(\Swagger\Client\ObjectSerializer::deserialize($response, '\Swagger\Client\Model\Cache', $httpHeader), $statusCode, $httpHeader);
            
        } catch (ApiException $e) {
            switch ($e->getCode()) { 
            case 200:
                $data = \Swagger\Client\ObjectSerializer::deserialize($e->getResponseBody(), '\Swagger\Client\Model\Cache', $e->getResponseHeaders());
                $e->setResponseObject($data);
                break;
            }
  
            throw $e;
        }
    }
    
    /**
     * deleteAllCache
     *
     * delete all CloudCaches
     *
     * @param string $app_id Id of CloudApp (required)
     * @param \Swagger\Client\Model\KeyBody $body master key of app (required)
     * @return \Swagger\Client\Model\CacheRequest[]
     * @throws \Swagger\Client\ApiException on non-2xx response
     */
    public function deleteAllCache($app_id, $body)
    {
        list($response, $statusCode, $httpHeader) = $this->deleteAllCacheWithHttpInfo ($app_id, $body);
        return $response; 
    }


    /**
     * deleteAllCacheWithHttpInfo
     *
     * delete all CloudCaches
     *
     * @param string $app_id Id of CloudApp (required)
     * @param \Swagger\Client\Model\KeyBody $body master key of app (required)
     * @return Array of \Swagger\Client\Model\CacheRequest[], HTTP status code, HTTP response headers (array of strings)
     * @throws \Swagger\Client\ApiException on non-2xx response
     */
    public function deleteAllCacheWithHttpInfo($app_id, $body)
    {
        
        // verify the required parameter 'app_id' is set
        if ($app_id === null) {
            throw new \InvalidArgumentException('Missing the required parameter $app_id when calling deleteAllCache');
        }
        // verify the required parameter 'body' is set
        if ($body === null) {
            throw new \InvalidArgumentException('Missing the required parameter $body when calling deleteAllCache');
        }
  
        // parse inputs
        $resourcePath = "cache/{app_id}";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = ApiClient::selectHeaderAccept(array('application/json'));
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = ApiClient::selectHeaderContentType(array('application/json'));
  
        
        
        // path params
        
        if ($app_id !== null) {
            $resourcePath = str_replace(
                "{" . "app_id" . "}",
                $this->apiClient->getSerializer()->toPathValue($app_id),
                $resourcePath
            );
        }
        // default format to json
        $resourcePath = str_replace("{format}", "json", $resourcePath);

        
        // body params
        $_tempBody = null;
        if (isset($body)) {
            $_tempBody = $body;
        }
  
        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath, 'DELETE',
                $queryParams, $httpBody,
                $headerParams, '\Swagger\Client\Model\CacheRequest[]'
            );
            
            if (!$response) {
                return array(null, $statusCode, $httpHeader);
            }

            return array(\Swagger\Client\ObjectSerializer::deserialize($response, '\Swagger\Client\Model\CacheRequest[]', $httpHeader), $statusCode, $httpHeader);
            
        } catch (ApiException $e) {
            switch ($e->getCode()) { 
            case 200:
                $data = \Swagger\Client\ObjectSerializer::deserialize($e->getResponseBody(), '\Swagger\Client\Model\CacheRequest[]', $e->getResponseHeaders());
                $e->setResponseObject($data);
                break;
            }
  
            throw $e;
        }
    }
    
    /**
     * deleteCache
     *
     * delete a CloudCache
     *
     * @param string $app_id Id of CloudApp (required)
     * @param string $cache_name Name of cache (required)
     * @param \Swagger\Client\Model\KeyBody $body master key of app (required)
     * @return \Swagger\Client\Model\CacheRequest
     * @throws \Swagger\Client\ApiException on non-2xx response
     */
    public function deleteCache($app_id, $cache_name, $body)
    {
        list($response, $statusCode, $httpHeader) = $this->deleteCacheWithHttpInfo ($app_id, $cache_name, $body);
        return $response; 
    }


    /**
     * deleteCacheWithHttpInfo
     *
     * delete a CloudCache
     *
     * @param string $app_id Id of CloudApp (required)
     * @param string $cache_name Name of cache (required)
     * @param \Swagger\Client\Model\KeyBody $body master key of app (required)
     * @return Array of \Swagger\Client\Model\CacheRequest, HTTP status code, HTTP response headers (array of strings)
     * @throws \Swagger\Client\ApiException on non-2xx response
     */
    public function deleteCacheWithHttpInfo($app_id, $cache_name, $body)
    {
        
        // verify the required parameter 'app_id' is set
        if ($app_id === null) {
            throw new \InvalidArgumentException('Missing the required parameter $app_id when calling deleteCache');
        }
        // verify the required parameter 'cache_name' is set
        if ($cache_name === null) {
            throw new \InvalidArgumentException('Missing the required parameter $cache_name when calling deleteCache');
        }
        // verify the required parameter 'body' is set
        if ($body === null) {
            throw new \InvalidArgumentException('Missing the required parameter $body when calling deleteCache');
        }
  
        // parse inputs
        $resourcePath = "cache/{app_id}/{cache_name}";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = ApiClient::selectHeaderAccept(array('application/json'));
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = ApiClient::selectHeaderContentType(array('application/json'));
  
        
        
        // path params
        
        if ($app_id !== null) {
            $resourcePath = str_replace(
                "{" . "app_id" . "}",
                $this->apiClient->getSerializer()->toPathValue($app_id),
                $resourcePath
            );
        }// path params
        
        if ($cache_name !== null) {
            $resourcePath = str_replace(
                "{" . "cache_name" . "}",
                $this->apiClient->getSerializer()->toPathValue($cache_name),
                $resourcePath
            );
        }
        // default format to json
        $resourcePath = str_replace("{format}", "json", $resourcePath);

        
        // body params
        $_tempBody = null;
        if (isset($body)) {
            $_tempBody = $body;
        }
  
        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath, 'DELETE',
                $queryParams, $httpBody,
                $headerParams, '\Swagger\Client\Model\CacheRequest'
            );
            
            if (!$response) {
                return array(null, $statusCode, $httpHeader);
            }

            return array(\Swagger\Client\ObjectSerializer::deserialize($response, '\Swagger\Client\Model\CacheRequest', $httpHeader), $statusCode, $httpHeader);
            
        } catch (ApiException $e) {
            switch ($e->getCode()) { 
            case 200:
                $data = \Swagger\Client\ObjectSerializer::deserialize($e->getResponseBody(), '\Swagger\Client\Model\CacheRequest', $e->getResponseHeaders());
                $e->setResponseObject($data);
                break;
            }
  
            throw $e;
        }
    }
    
    /**
     * deleteItem
     *
     * delete item from a cloud cache
     *
     * @param string $app_id Id of CloudApp (required)
     * @param string $cache_name Name of cache (required)
     * @param string $data_key key under which data to delete is cached (required)
     * @param \Swagger\Client\Model\KeyBody $body master key of app (required)
     * @return string
     * @throws \Swagger\Client\ApiException on non-2xx response
     */
    public function deleteItem($app_id, $cache_name, $data_key, $body)
    {
        list($response, $statusCode, $httpHeader) = $this->deleteItemWithHttpInfo ($app_id, $cache_name, $data_key, $body);
        return $response; 
    }


    /**
     * deleteItemWithHttpInfo
     *
     * delete item from a cloud cache
     *
     * @param string $app_id Id of CloudApp (required)
     * @param string $cache_name Name of cache (required)
     * @param string $data_key key under which data to delete is cached (required)
     * @param \Swagger\Client\Model\KeyBody $body master key of app (required)
     * @return Array of string, HTTP status code, HTTP response headers (array of strings)
     * @throws \Swagger\Client\ApiException on non-2xx response
     */
    public function deleteItemWithHttpInfo($app_id, $cache_name, $data_key, $body)
    {
        
        // verify the required parameter 'app_id' is set
        if ($app_id === null) {
            throw new \InvalidArgumentException('Missing the required parameter $app_id when calling deleteItem');
        }
        // verify the required parameter 'cache_name' is set
        if ($cache_name === null) {
            throw new \InvalidArgumentException('Missing the required parameter $cache_name when calling deleteItem');
        }
        // verify the required parameter 'data_key' is set
        if ($data_key === null) {
            throw new \InvalidArgumentException('Missing the required parameter $data_key when calling deleteItem');
        }
        // verify the required parameter 'body' is set
        if ($body === null) {
            throw new \InvalidArgumentException('Missing the required parameter $body when calling deleteItem');
        }
  
        // parse inputs
        $resourcePath = "cache/{app_id}/{cache_name}/item/{data_key}";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = ApiClient::selectHeaderAccept(array('application/json'));
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = ApiClient::selectHeaderContentType(array('application/json'));
  
        
        
        // path params
        
        if ($app_id !== null) {
            $resourcePath = str_replace(
                "{" . "app_id" . "}",
                $this->apiClient->getSerializer()->toPathValue($app_id),
                $resourcePath
            );
        }// path params
        
        if ($cache_name !== null) {
            $resourcePath = str_replace(
                "{" . "cache_name" . "}",
                $this->apiClient->getSerializer()->toPathValue($cache_name),
                $resourcePath
            );
        }// path params
        
        if ($data_key !== null) {
            $resourcePath = str_replace(
                "{" . "data_key" . "}",
                $this->apiClient->getSerializer()->toPathValue($data_key),
                $resourcePath
            );
        }
        // default format to json
        $resourcePath = str_replace("{format}", "json", $resourcePath);

        
        // body params
        $_tempBody = null;
        if (isset($body)) {
            $_tempBody = $body;
        }
  
        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath, 'DELETE',
                $queryParams, $httpBody,
                $headerParams, 'string'
            );
            
            if (!$response) {
                return array(null, $statusCode, $httpHeader);
            }

            return array(\Swagger\Client\ObjectSerializer::deserialize($response, 'string', $httpHeader), $statusCode, $httpHeader);
            
        } catch (ApiException $e) {
            switch ($e->getCode()) { 
            case 200:
                $data = \Swagger\Client\ObjectSerializer::deserialize($e->getResponseBody(), 'string', $e->getResponseHeaders());
                $e->setResponseObject($data);
                break;
            }
  
            throw $e;
        }
    }
    
    /**
     * getAllCache
     *
     * get all CloudCaches
     *
     * @param string $app_id Id of CloudApp (required)
     * @param \Swagger\Client\Model\KeyBody $body master key of app (required)
     * @return \Swagger\Client\Model\Cache[]
     * @throws \Swagger\Client\ApiException on non-2xx response
     */
    public function getAllCache($app_id, $body)
    {
        list($response, $statusCode, $httpHeader) = $this->getAllCacheWithHttpInfo ($app_id, $body);
        return $response; 
    }


    /**
     * getAllCacheWithHttpInfo
     *
     * get all CloudCaches
     *
     * @param string $app_id Id of CloudApp (required)
     * @param \Swagger\Client\Model\KeyBody $body master key of app (required)
     * @return Array of \Swagger\Client\Model\Cache[], HTTP status code, HTTP response headers (array of strings)
     * @throws \Swagger\Client\ApiException on non-2xx response
     */
    public function getAllCacheWithHttpInfo($app_id, $body)
    {
        
        // verify the required parameter 'app_id' is set
        if ($app_id === null) {
            throw new \InvalidArgumentException('Missing the required parameter $app_id when calling getAllCache');
        }
        // verify the required parameter 'body' is set
        if ($body === null) {
            throw new \InvalidArgumentException('Missing the required parameter $body when calling getAllCache');
        }
  
        // parse inputs
        $resourcePath = "cache/{app_id}";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = ApiClient::selectHeaderAccept(array('application/json'));
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = ApiClient::selectHeaderContentType(array('application/json'));
  
        
        
        // path params
        
        if ($app_id !== null) {
            $resourcePath = str_replace(
                "{" . "app_id" . "}",
                $this->apiClient->getSerializer()->toPathValue($app_id),
                $resourcePath
            );
        }
        // default format to json
        $resourcePath = str_replace("{format}", "json", $resourcePath);

        
        // body params
        $_tempBody = null;
        if (isset($body)) {
            $_tempBody = $body;
        }
  
        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath, 'POST',
                $queryParams, $httpBody,
                $headerParams, '\Swagger\Client\Model\Cache[]'
            );
            
            if (!$response) {
                return array(null, $statusCode, $httpHeader);
            }

            return array(\Swagger\Client\ObjectSerializer::deserialize($response, '\Swagger\Client\Model\Cache[]', $httpHeader), $statusCode, $httpHeader);
            
        } catch (ApiException $e) {
            switch ($e->getCode()) { 
            case 200:
                $data = \Swagger\Client\ObjectSerializer::deserialize($e->getResponseBody(), '\Swagger\Client\Model\Cache[]', $e->getResponseHeaders());
                $e->setResponseObject($data);
                break;
            }
  
            throw $e;
        }
    }
    
    /**
     * getAllItems
     *
     * get all items from a cloud cache
     *
     * @param string $app_id Id of CloudApp (required)
     * @param string $cache_name Name of cache (required)
     * @param \Swagger\Client\Model\KeyBody $body master key of app (required)
     * @return \Swagger\Client\Model\CacheItem[]
     * @throws \Swagger\Client\ApiException on non-2xx response
     */
    public function getAllItems($app_id, $cache_name, $body)
    {
        list($response, $statusCode, $httpHeader) = $this->getAllItemsWithHttpInfo ($app_id, $cache_name, $body);
        return $response; 
    }


    /**
     * getAllItemsWithHttpInfo
     *
     * get all items from a cloud cache
     *
     * @param string $app_id Id of CloudApp (required)
     * @param string $cache_name Name of cache (required)
     * @param \Swagger\Client\Model\KeyBody $body master key of app (required)
     * @return Array of \Swagger\Client\Model\CacheItem[], HTTP status code, HTTP response headers (array of strings)
     * @throws \Swagger\Client\ApiException on non-2xx response
     */
    public function getAllItemsWithHttpInfo($app_id, $cache_name, $body)
    {
        
        // verify the required parameter 'app_id' is set
        if ($app_id === null) {
            throw new \InvalidArgumentException('Missing the required parameter $app_id when calling getAllItems');
        }
        // verify the required parameter 'cache_name' is set
        if ($cache_name === null) {
            throw new \InvalidArgumentException('Missing the required parameter $cache_name when calling getAllItems');
        }
        // verify the required parameter 'body' is set
        if ($body === null) {
            throw new \InvalidArgumentException('Missing the required parameter $body when calling getAllItems');
        }
  
        // parse inputs
        $resourcePath = "cache/{app_id}/{cache_name}/items";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = ApiClient::selectHeaderAccept(array('application/json'));
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = ApiClient::selectHeaderContentType(array('application/json'));
  
        
        
        // path params
        
        if ($app_id !== null) {
            $resourcePath = str_replace(
                "{" . "app_id" . "}",
                $this->apiClient->getSerializer()->toPathValue($app_id),
                $resourcePath
            );
        }// path params
        
        if ($cache_name !== null) {
            $resourcePath = str_replace(
                "{" . "cache_name" . "}",
                $this->apiClient->getSerializer()->toPathValue($cache_name),
                $resourcePath
            );
        }
        // default format to json
        $resourcePath = str_replace("{format}", "json", $resourcePath);

        
        // body params
        $_tempBody = null;
        if (isset($body)) {
            $_tempBody = $body;
        }
  
        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath, 'POST',
                $queryParams, $httpBody,
                $headerParams, '\Swagger\Client\Model\CacheItem[]'
            );
            
            if (!$response) {
                return array(null, $statusCode, $httpHeader);
            }

            return array(\Swagger\Client\ObjectSerializer::deserialize($response, '\Swagger\Client\Model\CacheItem[]', $httpHeader), $statusCode, $httpHeader);
            
        } catch (ApiException $e) {
            switch ($e->getCode()) { 
            case 200:
                $data = \Swagger\Client\ObjectSerializer::deserialize($e->getResponseBody(), '\Swagger\Client\Model\CacheItem[]', $e->getResponseHeaders());
                $e->setResponseObject($data);
                break;
            }
  
            throw $e;
        }
    }
    
    /**
     * getCacheInfo
     *
     * get info about a CloudCache
     *
     * @param string $app_id Id of CloudApp (required)
     * @param string $cache_name Name of cache (required)
     * @param \Swagger\Client\Model\KeyBody $body master key of app (required)
     * @return \Swagger\Client\Model\Cache
     * @throws \Swagger\Client\ApiException on non-2xx response
     */
    public function getCacheInfo($app_id, $cache_name, $body)
    {
        list($response, $statusCode, $httpHeader) = $this->getCacheInfoWithHttpInfo ($app_id, $cache_name, $body);
        return $response; 
    }


    /**
     * getCacheInfoWithHttpInfo
     *
     * get info about a CloudCache
     *
     * @param string $app_id Id of CloudApp (required)
     * @param string $cache_name Name of cache (required)
     * @param \Swagger\Client\Model\KeyBody $body master key of app (required)
     * @return Array of \Swagger\Client\Model\Cache, HTTP status code, HTTP response headers (array of strings)
     * @throws \Swagger\Client\ApiException on non-2xx response
     */
    public function getCacheInfoWithHttpInfo($app_id, $cache_name, $body)
    {
        
        // verify the required parameter 'app_id' is set
        if ($app_id === null) {
            throw new \InvalidArgumentException('Missing the required parameter $app_id when calling getCacheInfo');
        }
        // verify the required parameter 'cache_name' is set
        if ($cache_name === null) {
            throw new \InvalidArgumentException('Missing the required parameter $cache_name when calling getCacheInfo');
        }
        // verify the required parameter 'body' is set
        if ($body === null) {
            throw new \InvalidArgumentException('Missing the required parameter $body when calling getCacheInfo');
        }
  
        // parse inputs
        $resourcePath = "cache/{app_id}/{cache_name}";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = ApiClient::selectHeaderAccept(array('application/json'));
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = ApiClient::selectHeaderContentType(array('application/json'));
  
        
        
        // path params
        
        if ($app_id !== null) {
            $resourcePath = str_replace(
                "{" . "app_id" . "}",
                $this->apiClient->getSerializer()->toPathValue($app_id),
                $resourcePath
            );
        }// path params
        
        if ($cache_name !== null) {
            $resourcePath = str_replace(
                "{" . "cache_name" . "}",
                $this->apiClient->getSerializer()->toPathValue($cache_name),
                $resourcePath
            );
        }
        // default format to json
        $resourcePath = str_replace("{format}", "json", $resourcePath);

        
        // body params
        $_tempBody = null;
        if (isset($body)) {
            $_tempBody = $body;
        }
  
        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath, 'POST',
                $queryParams, $httpBody,
                $headerParams, '\Swagger\Client\Model\Cache'
            );
            
            if (!$response) {
                return array(null, $statusCode, $httpHeader);
            }

            return array(\Swagger\Client\ObjectSerializer::deserialize($response, '\Swagger\Client\Model\Cache', $httpHeader), $statusCode, $httpHeader);
            
        } catch (ApiException $e) {
            switch ($e->getCode()) { 
            case 200:
                $data = \Swagger\Client\ObjectSerializer::deserialize($e->getResponseBody(), '\Swagger\Client\Model\Cache', $e->getResponseHeaders());
                $e->setResponseObject($data);
                break;
            }
  
            throw $e;
        }
    }
    
    /**
     * getItem
     *
     * get item from a cloud cache
     *
     * @param string $app_id Id of CloudApp (required)
     * @param string $cache_name Name of cache (required)
     * @param string $data_key key under which data should be got in cache (required)
     * @param \Swagger\Client\Model\KeyBody $body master key of app (required)
     * @return string
     * @throws \Swagger\Client\ApiException on non-2xx response
     */
    public function getItem($app_id, $cache_name, $data_key, $body)
    {
        list($response, $statusCode, $httpHeader) = $this->getItemWithHttpInfo ($app_id, $cache_name, $data_key, $body);
        return $response; 
    }


    /**
     * getItemWithHttpInfo
     *
     * get item from a cloud cache
     *
     * @param string $app_id Id of CloudApp (required)
     * @param string $cache_name Name of cache (required)
     * @param string $data_key key under which data should be got in cache (required)
     * @param \Swagger\Client\Model\KeyBody $body master key of app (required)
     * @return Array of string, HTTP status code, HTTP response headers (array of strings)
     * @throws \Swagger\Client\ApiException on non-2xx response
     */
    public function getItemWithHttpInfo($app_id, $cache_name, $data_key, $body)
    {
        
        // verify the required parameter 'app_id' is set
        if ($app_id === null) {
            throw new \InvalidArgumentException('Missing the required parameter $app_id when calling getItem');
        }
        // verify the required parameter 'cache_name' is set
        if ($cache_name === null) {
            throw new \InvalidArgumentException('Missing the required parameter $cache_name when calling getItem');
        }
        // verify the required parameter 'data_key' is set
        if ($data_key === null) {
            throw new \InvalidArgumentException('Missing the required parameter $data_key when calling getItem');
        }
        // verify the required parameter 'body' is set
        if ($body === null) {
            throw new \InvalidArgumentException('Missing the required parameter $body when calling getItem');
        }
  
        // parse inputs
        $resourcePath = "cache/{app_id}/{cache_name}/{data_key}/item";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = ApiClient::selectHeaderAccept(array('application/json'));
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = ApiClient::selectHeaderContentType(array('application/json'));
  
        
        
        // path params
        
        if ($app_id !== null) {
            $resourcePath = str_replace(
                "{" . "app_id" . "}",
                $this->apiClient->getSerializer()->toPathValue($app_id),
                $resourcePath
            );
        }// path params
        
        if ($cache_name !== null) {
            $resourcePath = str_replace(
                "{" . "cache_name" . "}",
                $this->apiClient->getSerializer()->toPathValue($cache_name),
                $resourcePath
            );
        }// path params
        
        if ($data_key !== null) {
            $resourcePath = str_replace(
                "{" . "data_key" . "}",
                $this->apiClient->getSerializer()->toPathValue($data_key),
                $resourcePath
            );
        }
        // default format to json
        $resourcePath = str_replace("{format}", "json", $resourcePath);

        
        // body params
        $_tempBody = null;
        if (isset($body)) {
            $_tempBody = $body;
        }
  
        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath, 'POST',
                $queryParams, $httpBody,
                $headerParams, 'string'
            );
            
            if (!$response) {
                return array(null, $statusCode, $httpHeader);
            }

            return array(\Swagger\Client\ObjectSerializer::deserialize($response, 'string', $httpHeader), $statusCode, $httpHeader);
            
        } catch (ApiException $e) {
            switch ($e->getCode()) { 
            case 200:
                $data = \Swagger\Client\ObjectSerializer::deserialize($e->getResponseBody(), 'string', $e->getResponseHeaders());
                $e->setResponseObject($data);
                break;
            }
  
            throw $e;
        }
    }
    
    /**
     * getItemsCount
     *
     * count items in a cloud cache
     *
     * @param string $app_id Id of CloudApp (required)
     * @param string $cache_name Name of cache (required)
     * @param \Swagger\Client\Model\KeyBody $body master key of app (required)
     * @return int
     * @throws \Swagger\Client\ApiException on non-2xx response
     */
    public function getItemsCount($app_id, $cache_name, $body)
    {
        list($response, $statusCode, $httpHeader) = $this->getItemsCountWithHttpInfo ($app_id, $cache_name, $body);
        return $response; 
    }


    /**
     * getItemsCountWithHttpInfo
     *
     * count items in a cloud cache
     *
     * @param string $app_id Id of CloudApp (required)
     * @param string $cache_name Name of cache (required)
     * @param \Swagger\Client\Model\KeyBody $body master key of app (required)
     * @return Array of int, HTTP status code, HTTP response headers (array of strings)
     * @throws \Swagger\Client\ApiException on non-2xx response
     */
    public function getItemsCountWithHttpInfo($app_id, $cache_name, $body)
    {
        
        // verify the required parameter 'app_id' is set
        if ($app_id === null) {
            throw new \InvalidArgumentException('Missing the required parameter $app_id when calling getItemsCount');
        }
        // verify the required parameter 'cache_name' is set
        if ($cache_name === null) {
            throw new \InvalidArgumentException('Missing the required parameter $cache_name when calling getItemsCount');
        }
        // verify the required parameter 'body' is set
        if ($body === null) {
            throw new \InvalidArgumentException('Missing the required parameter $body when calling getItemsCount');
        }
  
        // parse inputs
        $resourcePath = "cache/{app_id}/{cache_name}/items/count";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = ApiClient::selectHeaderAccept(array('application/json'));
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = ApiClient::selectHeaderContentType(array('application/json'));
  
        
        
        // path params
        
        if ($app_id !== null) {
            $resourcePath = str_replace(
                "{" . "app_id" . "}",
                $this->apiClient->getSerializer()->toPathValue($app_id),
                $resourcePath
            );
        }// path params
        
        if ($cache_name !== null) {
            $resourcePath = str_replace(
                "{" . "cache_name" . "}",
                $this->apiClient->getSerializer()->toPathValue($cache_name),
                $resourcePath
            );
        }
        // default format to json
        $resourcePath = str_replace("{format}", "json", $resourcePath);

        
        // body params
        $_tempBody = null;
        if (isset($body)) {
            $_tempBody = $body;
        }
  
        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath, 'POST',
                $queryParams, $httpBody,
                $headerParams, 'int'
            );
            
            if (!$response) {
                return array(null, $statusCode, $httpHeader);
            }

            return array(\Swagger\Client\ObjectSerializer::deserialize($response, 'int', $httpHeader), $statusCode, $httpHeader);
            
        } catch (ApiException $e) {
            switch ($e->getCode()) { 
            case 200:
                $data = \Swagger\Client\ObjectSerializer::deserialize($e->getResponseBody(), 'int', $e->getResponseHeaders());
                $e->setResponseObject($data);
                break;
            }
  
            throw $e;
        }
    }
    
    /**
     * set
     *
     * add item to a cloud cache
     *
     * @param string $app_id Id of CloudApp (required)
     * @param string $cache_name Name of cache (required)
     * @param string $data_key key under which data should be store in cache (required)
     * @param \Swagger\Client\Model\CacheRequest $body cache data and master key included got from this object (required)
     * @return string
     * @throws \Swagger\Client\ApiException on non-2xx response
     */
    public function set($app_id, $cache_name, $data_key, $body)
    {
        list($response, $statusCode, $httpHeader) = $this->setWithHttpInfo ($app_id, $cache_name, $data_key, $body);
        return $response; 
    }


    /**
     * setWithHttpInfo
     *
     * add item to a cloud cache
     *
     * @param string $app_id Id of CloudApp (required)
     * @param string $cache_name Name of cache (required)
     * @param string $data_key key under which data should be store in cache (required)
     * @param \Swagger\Client\Model\CacheRequest $body cache data and master key included got from this object (required)
     * @return Array of string, HTTP status code, HTTP response headers (array of strings)
     * @throws \Swagger\Client\ApiException on non-2xx response
     */
    public function setWithHttpInfo($app_id, $cache_name, $data_key, $body)
    {
        
        // verify the required parameter 'app_id' is set
        if ($app_id === null) {
            throw new \InvalidArgumentException('Missing the required parameter $app_id when calling set');
        }
        // verify the required parameter 'cache_name' is set
        if ($cache_name === null) {
            throw new \InvalidArgumentException('Missing the required parameter $cache_name when calling set');
        }
        // verify the required parameter 'data_key' is set
        if ($data_key === null) {
            throw new \InvalidArgumentException('Missing the required parameter $data_key when calling set');
        }
        // verify the required parameter 'body' is set
        if ($body === null) {
            throw new \InvalidArgumentException('Missing the required parameter $body when calling set');
        }
  
        // parse inputs
        $resourcePath = "cache/{app_id}/{cache_name}/{data_key}";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = ApiClient::selectHeaderAccept(array('application/json', 'text/plain;charset=utf-8'));
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = ApiClient::selectHeaderContentType(array('application/json'));
  
        
        
        // path params
        
        if ($app_id !== null) {
            $resourcePath = str_replace(
                "{" . "app_id" . "}",
                $this->apiClient->getSerializer()->toPathValue($app_id),
                $resourcePath
            );
        }// path params
        
        if ($cache_name !== null) {
            $resourcePath = str_replace(
                "{" . "cache_name" . "}",
                $this->apiClient->getSerializer()->toPathValue($cache_name),
                $resourcePath
            );
        }// path params
        
        if ($data_key !== null) {
            $resourcePath = str_replace(
                "{" . "data_key" . "}",
                $this->apiClient->getSerializer()->toPathValue($data_key),
                $resourcePath
            );
        }
        // default format to json
        $resourcePath = str_replace("{format}", "json", $resourcePath);

        
        // body params
        $_tempBody = null;
        if (isset($body)) {
            $_tempBody = $body;
        }
  
        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath, 'PUT',
                $queryParams, $httpBody,
                $headerParams, 'string'
            );
            
            if (!$response) {
                return array(null, $statusCode, $httpHeader);
            }

            return array(\Swagger\Client\ObjectSerializer::deserialize($response, 'string', $httpHeader), $statusCode, $httpHeader);
            
        } catch (ApiException $e) {
            switch ($e->getCode()) { 
            case 200:
                $data = \Swagger\Client\ObjectSerializer::deserialize($e->getResponseBody(), 'string', $e->getResponseHeaders());
                $e->setResponseObject($data);
                break;
            }
  
            throw $e;
        }
    }
    
}
