//
// CloudFile.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class CloudFile: JSONEncodable {

    public var id: String?
    public var _type: String?
    public var ACL: ACL?
    public var name: String?
    public var size: Float?
    public var url: String?
    public var expires: NSDate?
    public var contentType: String?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["_id"] = self.id
        nillableDictionary["_type"] = self._type
        nillableDictionary["ACL"] = self.ACL?.encodeToJSON()
        nillableDictionary["name"] = self.name
        nillableDictionary["size"] = self.size
        nillableDictionary["url"] = self.url
        nillableDictionary["expires"] = self.expires?.encodeToJSON()
        nillableDictionary["contentType"] = self.contentType
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
