//
// QueueMessage.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class QueueMessage: JSONEncodable {

    public var ACL: ACL?
    public var _type: String?
    public var expires: NSDate?
    public var id: String?
    public var delay: NSDate?
    public var timeout: Int?
    public var modifiedColumns: [String]?
    public var isModified: Bool?
    public var message: String?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["ACL"] = self.ACL?.encodeToJSON()
        nillableDictionary["_type"] = self._type
        nillableDictionary["expires"] = self.expires?.encodeToJSON()
        nillableDictionary["_id"] = self.id
        nillableDictionary["delay"] = self.delay?.encodeToJSON()
        nillableDictionary["timeout"] = self.timeout
        nillableDictionary["_modifiedColumns"] = self.modifiedColumns?.encodeToJSON()
        nillableDictionary["_isModified"] = self.isModified
        nillableDictionary["message"] = self.message
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
