=begin
CloudBoost Application API

Power your web or mobile application backend with cloudboost Database Service

OpenAPI spec version: 1.0.0
Contact: ben@cloudboost.io
Generated by: https://github.com/swagger-api/swagger-codegen.git

License: MIT
http://opensource.org/licenses/MIT

Terms of Service: https://cloudboost.io

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::CloudSearchApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'CloudSearchApi' do
  before do
    # run before each test
    @instance = SwaggerClient::CloudSearchApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CloudSearchApi' do
    it 'should create an instact of CloudSearchApi' do
      @instance.should be_a(SwaggerClient::CloudSearchApi)
    end
  end

  # unit tests for search
  # search for cloudobjects following the criteria defined herein
  # 
  # @param app_id CloudApp id
  # @param table_name cloud table name
  # @param body query body
  # @param [Hash] opts the optional parameters
  # @return [Array<CloudObject>]
  describe 'search test' do
    it "should work" do
      # assertion here
      # should be_a()
      # should be_nil
      # should ==
      # should_not ==
    end
  end

end
