=begin
CloudBoost Application API

Power your web or mobile application backend with cloudboost Database Service

OpenAPI spec version: 1.0.0
Contact: ben@cloudboost.io
Generated by: https://github.com/swagger-api/swagger-codegen.git

License: MIT
http://opensource.org/licenses/MIT

Terms of Service: https://cloudboost.io

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::CloudRoleApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'CloudRoleApi' do
  before do
    # run before each test
    @instance = SwaggerClient::CloudRoleApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CloudRoleApi' do
    it 'should create an instact of CloudRoleApi' do
      @instance.should be_a(SwaggerClient::CloudRoleApi)
    end
  end

  # unit tests for create_role
  # create a new cloudrole
  # 
  # @param app_id ID of app
  # @param body request body
  # @param [Hash] opts the optional parameters
  # @return [CloudRole]
  describe 'create_role test' do
    it "should work" do
      # assertion here
      # should be_a()
      # should be_nil
      # should ==
      # should_not ==
    end
  end

end
