using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing BoolQuery
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class BoolQueryTests
    {
        private BoolQuery instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new BoolQuery();
        }
    
        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }   

        /// <summary>
        /// Test an instance of BoolQuery
        /// </summary>
        [Test]
        public void BoolQueryInstanceTest()
        {
            Assert.IsInstanceOf<BoolQuery> (instance, "instance is a BoolQuery");
        }

        
        /// <summary>
        /// Test the property '_Bool' 
        /// </summary>
        [Test]
        public void _BoolTest()
        {
            // TODO: unit test for the property '_Bool' 
        }
        

    }

}
