using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing CloudQueryId
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CloudQueryIdTests
    {
        private CloudQueryId instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new CloudQueryId();
        }
    
        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }   

        /// <summary>
        /// Test an instance of CloudQueryId
        /// </summary>
        [Test]
        public void CloudQueryIdInstanceTest()
        {
            Assert.IsInstanceOf<CloudQueryId> (instance, "instance is a CloudQueryId");
        }

        
        /// <summary>
        /// Test the property 'IncludeList' 
        /// </summary>
        [Test]
        public void IncludeListTest()
        {
            // TODO: unit test for the property 'IncludeList' 
        }
        
        /// <summary>
        /// Test the property 'Include' 
        /// </summary>
        [Test]
        public void IncludeTest()
        {
            // TODO: unit test for the property 'Include' 
        }
        
        /// <summary>
        /// Test the property 'Id' 
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO: unit test for the property 'Id' 
        }
        

    }

}
