using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing CloudTableApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class CloudTableApiTests
    {
        private CloudTableApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
           instance = new CloudTableApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CloudTableApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            Assert.IsInstanceOf<CloudTableApi> (instance, "instance is a CloudTableApi");
        }

        
        /// <summary>
        /// Test DeleteTable
        /// </summary>
        [Test]
        public void DeleteTableTest()
        {
            // TODO: add unit test for the method 'DeleteTable'
            string tableName = null; // TODO: replace null with proper value
            string appId = null; // TODO: replace null with proper value
            CloudTableSave body = null; // TODO: replace null with proper value
            
            var response = instance.DeleteTable(tableName, appId, body);
            Assert.IsInstanceOf<CloudTable> (response, "response is CloudTable"); 
        }
        
        /// <summary>
        /// Test Get
        /// </summary>
        [Test]
        public void GetTest()
        {
            // TODO: add unit test for the method 'Get'
            string tableName = null; // TODO: replace null with proper value
            string appId = null; // TODO: replace null with proper value
            KeyBody body = null; // TODO: replace null with proper value
            
            var response = instance.Get(tableName, appId, body);
            Assert.IsInstanceOf<CloudTable> (response, "response is CloudTable"); 
        }
        
        /// <summary>
        /// Test GetAll
        /// </summary>
        [Test]
        public void GetAllTest()
        {
            // TODO: add unit test for the method 'GetAll'
            string appId = null; // TODO: replace null with proper value
            KeyBody body = null; // TODO: replace null with proper value
            
            instance.GetAll(appId, body);
             
        }
        
        /// <summary>
        /// Test Save
        /// </summary>
        [Test]
        public void SaveTest()
        {
            // TODO: add unit test for the method 'Save'
            string tableName = null; // TODO: replace null with proper value
            string appId = null; // TODO: replace null with proper value
            CloudTableSave body = null; // TODO: replace null with proper value
            
            var response = instance.Save(tableName, appId, body);
            Assert.IsInstanceOf<CloudTable> (response, "response is CloudTable"); 
        }
        
    }

}
