using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing CloudFile
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CloudFileTests
    {
        private CloudFile instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new CloudFile();
        }
    
        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }   

        /// <summary>
        /// Test an instance of CloudFile
        /// </summary>
        [Test]
        public void CloudFileInstanceTest()
        {
            Assert.IsInstanceOf<CloudFile> (instance, "instance is a CloudFile");
        }

        
        /// <summary>
        /// Test the property 'Id' 
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO: unit test for the property 'Id' 
        }
        
        /// <summary>
        /// Test the property 'Type' 
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO: unit test for the property 'Type' 
        }
        
        /// <summary>
        /// Test the property 'ACL' 
        /// </summary>
        [Test]
        public void ACLTest()
        {
            // TODO: unit test for the property 'ACL' 
        }
        
        /// <summary>
        /// Test the property 'Name' 
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO: unit test for the property 'Name' 
        }
        
        /// <summary>
        /// Test the property 'Size' 
        /// </summary>
        [Test]
        public void SizeTest()
        {
            // TODO: unit test for the property 'Size' 
        }
        
        /// <summary>
        /// Test the property 'Url' 
        /// </summary>
        [Test]
        public void UrlTest()
        {
            // TODO: unit test for the property 'Url' 
        }
        
        /// <summary>
        /// Test the property 'Expires' 
        /// </summary>
        [Test]
        public void ExpiresTest()
        {
            // TODO: unit test for the property 'Expires' 
        }
        
        /// <summary>
        /// Test the property 'ContentType' 
        /// </summary>
        [Test]
        public void ContentTypeTest()
        {
            // TODO: unit test for the property 'ContentType' 
        }
        

    }

}
