using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Column
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ColumnTests
    {
        private Column instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new Column();
        }
    
        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }   

        /// <summary>
        /// Test an instance of Column
        /// </summary>
        [Test]
        public void ColumnInstanceTest()
        {
            Assert.IsInstanceOf<Column> (instance, "instance is a Column");
        }

        
        /// <summary>
        /// Test the property 'Name' 
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO: unit test for the property 'Name' 
        }
        
        /// <summary>
        /// Test the property 'DataType' 
        /// </summary>
        [Test]
        public void DataTypeTest()
        {
            // TODO: unit test for the property 'DataType' 
        }
        
        /// <summary>
        /// Test the property 'Type' 
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO: unit test for the property 'Type' 
        }
        
        /// <summary>
        /// Test the property 'Required' 
        /// </summary>
        [Test]
        public void RequiredTest()
        {
            // TODO: unit test for the property 'Required' 
        }
        
        /// <summary>
        /// Test the property 'Unique' 
        /// </summary>
        [Test]
        public void UniqueTest()
        {
            // TODO: unit test for the property 'Unique' 
        }
        
        /// <summary>
        /// Test the property 'RelatedTo' 
        /// </summary>
        [Test]
        public void RelatedToTest()
        {
            // TODO: unit test for the property 'RelatedTo' 
        }
        
        /// <summary>
        /// Test the property 'RelationType' 
        /// </summary>
        [Test]
        public void RelationTypeTest()
        {
            // TODO: unit test for the property 'RelationType' 
        }
        
        /// <summary>
        /// Test the property 'IsDeletable' 
        /// </summary>
        [Test]
        public void IsDeletableTest()
        {
            // TODO: unit test for the property 'IsDeletable' 
        }
        
        /// <summary>
        /// Test the property 'IsEditable' 
        /// </summary>
        [Test]
        public void IsEditableTest()
        {
            // TODO: unit test for the property 'IsEditable' 
        }
        
        /// <summary>
        /// Test the property 'IsRenamable' 
        /// </summary>
        [Test]
        public void IsRenamableTest()
        {
            // TODO: unit test for the property 'IsRenamable' 
        }
        

    }

}
