using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Filtered
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class FilteredTests
    {
        private Filtered instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new Filtered();
        }
    
        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }   

        /// <summary>
        /// Test an instance of Filtered
        /// </summary>
        [Test]
        public void FilteredInstanceTest()
        {
            Assert.IsInstanceOf<Filtered> (instance, "instance is a Filtered");
        }

        
        /// <summary>
        /// Test the property 'Query' 
        /// </summary>
        [Test]
        public void QueryTest()
        {
            // TODO: unit test for the property 'Query' 
        }
        
        /// <summary>
        /// Test the property 'Filter' 
        /// </summary>
        [Test]
        public void FilterTest()
        {
            // TODO: unit test for the property 'Filter' 
        }
        

    }

}
