<?php
/**
 * CloudCacheApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2016 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client\Api;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiClient;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * CloudCacheApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class CloudCacheApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running each test case
     */
    public static function setUpBeforeClass() {

    }

    /**
     * Clean up after running each test case
     */
    public static function tearDownAfterClass() {

    }

    
    /**
     * Test case for clearCache
     *
     * clear all items from a cloud cache
     *
     */
    public function test_clearCache() {

    }
    
    /**
     * Test case for createCache
     *
     * create a cloud cache
     *
     */
    public function test_createCache() {

    }
    
    /**
     * Test case for deleteAllCache
     *
     * delete all CloudCaches
     *
     */
    public function test_deleteAllCache() {

    }
    
    /**
     * Test case for deleteCache
     *
     * delete a CloudCache
     *
     */
    public function test_deleteCache() {

    }
    
    /**
     * Test case for deleteItem
     *
     * delete item from a cloud cache
     *
     */
    public function test_deleteItem() {

    }
    
    /**
     * Test case for getAllCache
     *
     * get all CloudCaches
     *
     */
    public function test_getAllCache() {

    }
    
    /**
     * Test case for getAllItems
     *
     * get all items from a cloud cache
     *
     */
    public function test_getAllItems() {

    }
    
    /**
     * Test case for getCacheInfo
     *
     * get info about a CloudCache
     *
     */
    public function test_getCacheInfo() {

    }
    
    /**
     * Test case for getItem
     *
     * get item from a cloud cache
     *
     */
    public function test_getItem() {

    }
    
    /**
     * Test case for getItemsCount
     *
     * count items in a cloud cache
     *
     */
    public function test_getItemsCount() {

    }
    
    /**
     * Test case for set
     *
     * add item to a cloud cache
     *
     */
    public function test_set() {

    }
    
}
