# coding: utf-8

"""
Copyright 2016 SmartBear Software

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

    Ref: https://github.com/swagger-api/swagger-codegen
"""

from pprint import pformat
from six import iteritems


class SearchQuery(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self):
        """
        SearchQuery - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'must_not': 'list[str]',
            'should': 'list[str]',
            'must': 'list[str]'
        }

        self.attribute_map = {
            'must_not': 'must_not',
            'should': 'should',
            'must': 'must'
        }

        self._must_not = None
        self._should = None
        self._must = None

    @property
    def must_not(self):
        """
        Gets the must_not of this SearchQuery.


        :return: The must_not of this SearchQuery.
        :rtype: list[str]
        """
        return self._must_not

    @must_not.setter
    def must_not(self, must_not):
        """
        Sets the must_not of this SearchQuery.


        :param must_not: The must_not of this SearchQuery.
        :type: list[str]
        """
        self._must_not = must_not

    @property
    def should(self):
        """
        Gets the should of this SearchQuery.


        :return: The should of this SearchQuery.
        :rtype: list[str]
        """
        return self._should

    @should.setter
    def should(self, should):
        """
        Sets the should of this SearchQuery.


        :param should: The should of this SearchQuery.
        :type: list[str]
        """
        self._should = should

    @property
    def must(self):
        """
        Gets the must of this SearchQuery.


        :return: The must of this SearchQuery.
        :rtype: list[str]
        """
        return self._must

    @must.setter
    def must(self, must):
        """
        Sets the must of this SearchQuery.


        :param must: The must of this SearchQuery.
        :type: list[str]
        """
        self._must = must

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other

